apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
      containers:
      - name: beta
        image: redis
        resources:
          requests:
            cpu: "500m"
            memory: "1G"
          limits:
            memory: "2G"
            cpu: "500m"
        ports:
        - containerPort: 8080
